spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydb  # 'spring-boot-postgresql' 대신 'db'로 변경
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # 시간대 설정
  jackson:
    time-zone: Asia/Seoul
